// USER REDUCERS TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
// export const SET_USER = 'SET_USER';
// export const LOADING_USER = 'LOADING_USER';

// UI REDUCERS TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const LOADING_DATA = 'LOADING_DATA';

// DATA REDUCERS TYPES
export const SET_FUTURE_ORDERS = 'SET_FUTURE_ORDERS';
export const SET_PAST_ORDERS = 'SET_PAST_ORDERS';
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_BREADS = 'SET_BREADS';